export const getMockStationData = (id: string) => {
  return {
    id: parseInt(id),
    name: "Bole International Airport EV Hub",
    address: "Bole International Airport",
    city: "Addis Ababa",
    lat: 8.9779,
    lng: 38.7993,
    status: "ACTIVE",
    isVerified: true,
    rating: 4.92,
    totalReviews: 342,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    chargingPoints: [
      {
        id: 101,
        stationId: 1,
        connectorType: "CCS",
        powerKw: 150,
        status: "AVAILABLE",
        averageSessionDuration: 45,
        slotNumber: "A1",
        chargingSpeed: "ULTRA_FAST",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 102,
        stationId: 1,
        connectorType: "TYPE2",
        powerKw: 22,
        status: "OCCUPIED",
        averageSessionDuration: 120,
        slotNumber: "A2",
        chargingSpeed: "SLOW",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 103,
        stationId: 1,
        connectorType: "CHADEMO",
        powerKw: 50,
        status: "AVAILABLE",
        averageSessionDuration: 60,
        slotNumber: "B1",
        chargingSpeed: "FAST",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 104,
        stationId: 1,
        connectorType: "CCS",
        powerKw: 350,
        status: "AVAILABLE",
        averageSessionDuration: 25,
        slotNumber: "C1",
        chargingSpeed: "ULTRA_FAST",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 105,
        stationId: 1,
        connectorType: "TYPE2",
        powerKw: 11,
        status: "AVAILABLE",
        averageSessionDuration: 180,
        slotNumber: "D1",
        chargingSpeed: "SLOW",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    tariffs: [
      {
        id: 1001,
        stationId: 1,
        pricePerKwh: "0.28",
        pricePerMinute: null,
        idleFeePerMinute: "0.12",
        currency: "USD",
        validFrom: new Date().toISOString(),
        validTo: null,
        createdAt: new Date().toISOString(),
      },
    ],
    ratings: [
      {
        id: 1,
        stationId: 1,
        userId: "user1",
        score: 5,
        comment: "Great location, fast charging",
        createdAt: new Date().toISOString(),
      },
      {
        id: 2,
        stationId: 1,
        userId: "user2",
        score: 4.8,
        comment: "Clean and efficient",
        createdAt: new Date().toISOString(),
      },
      {
        id: 3,
        stationId: 1,
        userId: "user3",
        score: 5,
        comment: "Best EV station in Addis!",
        createdAt: new Date().toISOString(),
      },
    ],
    documents: [],
    images: [],
  }
}

export const formatCurrency = (amount: number, currency = "USD") => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
  }).format(amount)
}
