import "./globals.css"

import type { Metadata } from "next"
import "mapbox-gl/dist/mapbox-gl.css"
import AppProvider from "./Provider"

export const metadata: Metadata = {
  title: "HabeshaGo",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
  session?: any
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
