export { Navigation } from "./navigation"
export { HeroSection } from "./hero-section"
export { PaymentPartnersSection } from "./payment-partners"
export { ServicesSection } from "./services-section"
export { InteractivePreviewSection } from "./interactive-preview"
export { default as HowWeWorks } from "./how-we-work"
export { TestimonialsSection } from "./testimonials"
export { FAQSection } from "./faq-section"
export { Footer } from "./footer"
